version: '2.2'

services:
  app:
    image: 'wyrgorod:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - vars-spring.env
          
  db:
    image: 'postgres:13'
    container_name: db
    env_file:
      - vars-postgres.env
