CREATE TABLE artist
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_artist PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE image
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    content      OID,
    content_type VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    artist_id    BIGINT                                  NOT NULL,
    publisher_id BIGINT,
    price        DECIMAL(19, 2),
    medium       INTEGER,
    image_id     BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE news_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    artist_id   BIGINT,
    CONSTRAINT pk_news_item PRIMARY KEY (id)
);

CREATE TABLE order_
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    amount      DECIMAL(19, 2),
    CONSTRAINT pk_order_ PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id  BIGINT                                  NOT NULL,
    quantity INTEGER                                 NOT NULL,
    order_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (id)
);

CREATE TABLE publisher
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_publisher PRIMARY KEY (id)
);

CREATE TABLE user_
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login         VARCHAR(50)                             NOT NULL,
    password_hash VARCHAR(60)                             NOT NULL,
    first_name    VARCHAR(50),
    last_name     VARCHAR(50),
    email         VARCHAR(254),
    activated     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_ PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);

ALTER TABLE publisher
    ADD CONSTRAINT uc_publisher_name UNIQUE (name);

ALTER TABLE user_
    ADD CONSTRAINT uc_user__email UNIQUE (email);

ALTER TABLE user_
    ADD CONSTRAINT uc_user__login UNIQUE (login);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_ARTIST FOREIGN KEY (artist_id) REFERENCES artist (id);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE item
    ADD CONSTRAINT FK_ITEM_ON_PUBLISHER FOREIGN KEY (publisher_id) REFERENCES publisher (id);

ALTER TABLE news_item
    ADD CONSTRAINT FK_NEWS_ITEM_ON_ARTIST FOREIGN KEY (artist_id) REFERENCES artist (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_ (id);

ALTER TABLE order_
    ADD CONSTRAINT FK_ORDER__ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);